# Generated by Django 3.1.12 on 2023-12-31 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_auto_20231202_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='medication',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='reminder',
            name='next_reminder_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
